### ISSUE TITLE
Audio plays even if no more tries (using keyboard)

### ISSUE THREAD

**Issue by fnoks** [otacke/h5p-dictation#36]
You can play the audio using the keyboard (the space key) even if there are no more tries.

**Comment by otacke** [comment]
On it ...

**Comment by otacke** [comment]
@fnoks Would it be okay to add a disable/enable function to H5P.Audio instead of trying to work around that issue in Dictation?

**Comment by otacke** [comment]
@fnoks Done in latest commit in connection with https://github.com/h5p/h5p-audio/pull/19
