### ISSUE TITLE
Add option to consider spaces as "words", too

### ISSUE THREAD

**Issue by otacke** [otacke/h5p-dictation#45]
Will require at least
- change data structure for sentences
- add option to semantics
- update translations
- thorough testing especially for the align functions

**Comment by tdjac0bs** [comment]
This can be achieved with my PR, if you define the separator as `@` your sentence could be:
This@ @space@ @counts@ @as@ @word.

**Comment by otacke** [comment]
@tdjac0bs True, nice side effect! Thanks for your contribution.
