### ISSUE TITLE
Instructions on how to get it running from source

### ISSUE THREAD

**Issue by tdjac0bs** [otacke/h5p-dictation#66]
Hello, it would be good if you can share instructions how we can get this running from the source.

What I did so far is:
- Downloading a .h5p file
- Rename to .zip
- Replace contents of folder "H5P.Dictation-1.0"

However, it's not a direct replacement, as I get different file names when I run the build script.

Any tips or references are appreciated.

**Comment by otacke** [comment]
Why doesn't anyone read readmes anymore nowadays? ;-)

https://github.com/otacke/h5p-dictation#readme

**Comment by tdjac0bs** [comment]
hello @otacke, I think you didn't read my question completely, because in the question I state that I executed the build script ( after carefuly reading the readme )...

**Comment by otacke** [comment]
@tdjac0bs You got me there. Sorry. You will have to then pack the distribution files into an H5P library file using the `pack` command of H5P CLI, see https://h5p.org/h5p-cli-guide. You can zip that stuff manually, too, but that'd require some extra steps and come with obstacles.

**Comment by tdjac0bs** [comment]
No problem at all.

Also, I understand that the question I'm asking is more about h5p than about your library, but in order to contribute with the library, we need to understand how to proceed.

Actually after you shared [this link](https://h5p.org/development-environment ) I was able to get to [this tutorial](https://h5p.org/development-environment-docker) .

Will invest a few hours in this and post back here, just in case it helps someone else.

**Comment by otacke** [comment]
If it's just about building an H5P library from sources, then
https://youtube.com/playlist?list=PL4lOawnmqTnHuQIBYz7K7LkdTybL3Ui7T might be more helpful.

**Comment by tdjac0bs** [comment]
yes, this video cover all my questions. I see you added it in README, well done!
thank you

**Comment by otacke** [comment]
@tdjac0bs Thank *you* for pointing out that this info was missing!
