### ISSUE TITLE
Alternative correct answers

### ISSUE THREAD

**Issue by tdjac0bs** [otacke/h5p-dictation#67]
Hello, I've understood that I can have multiple tokens for a same word:

In this example: "Dom|Don Juan", it would accept both "Dom Juan" and "Don Juan"

How could we encode these two correct answers?

- Le relais Sintrom-Fraxiparine aura lieu à l'hôpital.
- Le relais Sintrom - Fraxiparine aura lieu à l'hôpital.

**Comment by otacke** [comment]
You are doing in correct in theory, but the regular solution and alternative solutions cannot have different numbers of words.

**Comment by tdjac0bs** [comment]
I'm wondering if we could use a different ( configurable ) separator for words.

Imagine this:

- Word separator ( default is space): "*" 

Sentence:
```
Le*relais*Sintrom-Fraxiparine|Sintrom - Fraxiparine*aura*lieu*à*l'hôpital.
```

would it be acceptable if we send a PR implementing this option?

**Comment by otacke** [comment]
Of course! Hope my data structure has not become too crazy for that option. It kind of grew as I added more of the features that users requested.

**Comment by tdjac0bs** [comment]
It seems I got it working.

For the configuration: `Le @@relais @@Sintrom-Fraxiparine |Sintrom - Fraxiparine @@aura @@lieu @@à @@l'hôpital.`

We can have both: `Le relais Sintrom-Fraxiparine aura lieu à l'hôpital.`
![image](https://user-images.githubusercontent.com/2075267/118190706-e12df680-b419-11eb-9d7a-23e07227e51c.png)

And `Le relais Sintrom - Fraxiparine aura lieu à l'hôpital.`
![image](https://user-images.githubusercontent.com/2075267/118190739-ec812200-b419-11eb-9fc8-e8eeaab42acb.png)

**Comment by otacke** [comment]
Nice!

**Comment by tdjac0bs** [comment]
This feature has been implemented in [this PR](https://github.com/otacke/h5p-dictation/pull/68), closing the issue.
