### ISSUE TITLE
How to force a specific language

### ISSUE THREAD

**Issue by tdjac0bs** [otacke/h5p-dictation#74]
Hello, I would like to force H5P-DICTATION to use a specific language for tests, is there any global variable I can define, so H5P tells this plugin that it should render the content in other language?

**Comment by otacke** [comment]
Not that I know of. Please use the [H5P forum](https://h5p.org/forum) to ask general questions about H5P, not issues on github.

**Comment by JacobsTiago** [comment]
thank you @otacke for pointing the right place to make the question.

Just in case someone reach this issue in future, [here is the forum post](https://h5p.org/node/1197084).
