### ISSUE TITLE
Could you imclude turkish to Fix language files files

### ISSUE THREAD

**Issue by sberger** [otacke/h5p-dictation#75]
In the "Text Overrides and Translations" part of "Dictation" in H5P, there is no option for Turkish. Can this be added? Our Turkish teachers would like to use it.

**Comment by otacke** [comment]
Hi @sberger!

I don't speak Turkish, so I cannot add a language template. But your teachers can contribute the translation if they need it. IMHO, the easiest way is to use https://translate-h5p.tk/ for that purpose.

Cheers,
Oliver
