### ISSUE TITLE
Add skip button

### ISSUE THREAD

**Issue by TiagoJacobs** [otacke/h5p-dictation#80]
It would be useful to have a "Skip" button on side of the "Retry".

It means the user is saying: ok, this score is enough, go ahead.

1. Is there any way to do it right now?
2. If not, would you be interested in receiving a PR with this feature?

Example:
![image](https://user-images.githubusercontent.com/2075267/128115361-d0d2c35a-366f-4acb-9fc1-4ebc4581ee80.png)

**Comment by otacke** [comment]
@TiagoJacobs And what would that button do? You're done already. What would you be skipping?

**Comment by TiagoJacobs** [comment]
Imagine we have a page with with 10 different sentences ( and we want individual scores for each sentence ) and instead of showing all sentences together, we want to show it one after other ( type, see score, try again, see score, move next ).

We achieved it by having multiple contents in this same page ( loading next content when `success=true` ).

However, user has no way to say: "I don't want to retry, this is was final attempt".

Does it make sense?

**Comment by TiagoJacobs** [comment]
continuing... 

Maybe a better name could be "Finish", and we would only send `completion=true` when it's clicked ( in case this button is toggled visible )

**Comment by TiagoJacobs** [comment]
So we would have a config:
```
showFinishButton: true
```

And when this config is true, the button would be displayed, and the `xAPI` event would report `completion=false` for the "Check" button, and `completion=true` for the "Finish" button.

**Comment by otacke** [comment]
@TiagoJacobs So you are referring to some special requirement of the platform? In that case, the platform should inject that button using H5P's alter_scripts hook or H5P core should offer a solution to add such a button. IMHO it does not make sense to put it into a/every single content type.
