### ISSUE TITLE
Emit a "attempted" xAPI event when you click "Try again"

### ISSUE THREAD

**Issue by TiagoJacobs** [otacke/h5p-dictation#81]
Everytime we open an activity we see a xAPI event with verb "http://adlnet.gov/expapi/verbs/attempted".

However, when you click on "try again", we don't see this event.

In order to make the "outside" UI consistent, I would need this event to be triggered.

Does it make sense for the project? 

I mean, I can do this change, but not sure if it's desired.

**Comment by otacke** [comment]
@TiagoJacobs That event is triggered by H5P.Question via  calling `setActivityStarted` on H5P core, not by Dictation. Please discuss terms of re-emitting it and the meaning of `attempted` verb with the H5P core team. If re-emitting is fine, then it should be done for all content types consistently, and then it does not make sense to implement that into every single content type but into H5P-Question.
